apiVersion: v1
kind: Secret
metadata:
  name: bank-app-secrets
type: Opaque
data:
  DATABASE_URL: {{ .Values.secrets.DATABASE_URL | b64enc }}
  CORE_API_URL: {{ .Values.secrets.CORE_API_URL | b64enc }}
  PORT: {{ .Values.secrets.PORT | b64enc }}
  DEBUG: {{ .Values.secrets.DEBUG | b64enc }}