apiVersion: v1
kind: Secret
metadata:
  name: go-secrets
type: Opaque
data:
  AWS_REGION: {{ .Values.go.secrets.AWS_REGION | b64enc | quote }}
  AWS_ACCESS_KEY_ID: {{ .Values.go.secrets.AWS_ACCESS_KEY_ID | b64enc | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.go.secrets.AWS_SECRET_ACCESS_KEY | b64enc | quote }}
  PORT: {{ .Values.go.secrets.PORT | b64enc | quote }}
  TRANSACTION_SERVICE_URL: {{ .Values.go.secrets.TRANSACTION_SERVICE_URL | b64enc | quote }}