apiVersion: v1
kind: Service
metadata:
  name: corebank-api
  labels:
    app: corebank-api
spec:
  # type: NodePort
  type: LoadBalancer
  selector:
    # app: go-api
    app: corebank-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080 

