apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1
spec:
  replicas: {{ .Values.app1.replicaCount }}
  selector:
    matchLabels:
      app: app1
  template:
    metadata:
      labels:
        app: app1
    spec:
      containers:
      - name: nginx
        image: "{{ .Values.app1.image }}:{{ .Values.app1.tag }}"
        ports:
        - containerPort: 80
        volumeMounts:
        - name: html
          mountPath: /usr/share/nginx/html
      volumes:
      - name: html
        configMap:
          name: app1-html