apiVersion: apps/v1
kind: Deployment
metadata:
  name: app2
spec:
  replicas: {{ .Values.app2.replicaCount }}
  selector:
    matchLabels:
      app: app2
  template:
    metadata:
      labels:
        app: app2
    spec:
      containers:
      - name: nginx
        image: "{{ .Values.app2.image }}:{{ .Values.app2.tag }}"
        ports:
        - containerPort: 80
        volumeMounts:
        - name: html
          mountPath: /usr/share/nginx/html
      volumes:
      - name: html
        configMap:
          name: app2-html