apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "node-metrics-exporter.fullname" . }}
  labels:
    {{- include "node-metrics-exporter.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "node-metrics-exporter.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- toYaml .Values.podAnnotations | nindent 8 }}
      labels:
        {{- include "node-metrics-exporter.labels" . | nindent 8 }}
    spec:
      hostNetwork: true
      hostPID: true
      containers:
      - name: node-exporter
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        args:
        - --path.procfs=/host/proc
        - --path.sysfs=/host/sys
        - --path.rootfs=/host/root
        - --no-collector.wifi
        - --no-collector.hwmon
        - --collector.filesystem.ignored-mount-points=^/(dev|proc|sys|var/lib/docker/.+)($|/)
        - --collector.netclass.ignored-devices=^lo$
        ports:
        - containerPort: {{ .Values.service.targetPort }}
          name: metrics
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        volumeMounts:
        - name: proc
          mountPath: /host/proc
          readOnly: true
        - name: sys
          mountPath: /host/sys
          readOnly: true
        - name: root
          mountPath: /host/root
          readOnly: true
      volumes:
      - name: proc
        hostPath:
          path: /proc
      - name: sys
        hostPath:
          path: /sys
      - name: root
        hostPath:
          path: /
      tolerations:
        {{- toYaml .Values.tolerations | nindent 8 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}