apiVersion: v1
kind: Service
metadata:
  name: {{ include "node-metrics-exporter.fullname" . }}
  labels:
    {{- include "node-metrics-exporter.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.service.annotations | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "node-metrics-exporter.selectorLabels" . | nindent 4 }}